# use Ganache's forked mainnet mode as the default network
networks:
  default: development

autofetch_sources: true

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0

compiler:
  solc:
    version: 0.8.13
    remappings:
      - "@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.5.0/contracts"

reports:
  exclude_contracts:
    - SafeERC20
    - Address
    - Token